language: php

php:
  - 7.1

addons:
  mariadb: '10.0'

env:
  - TRAVIS_SECURE_ENV_VARS=true

before_script:
  - cp .env.travis .env
  - mysql -e 'CREATE DATABASE submit_api;'
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan jwt:generate

script:
  - vendor/bin/phpunit

deploy:
  provider: heroku
  app: submit-api
  api_key: 
    secure: heroku-api
  strategy: git
