language: php

php:
  - 7.1

before_script:
  - cp .env.travis .env
  - mysql -e 'create database submit-api;'
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan jwt:generate

script:
  - vendor/bin/phpunit
